from tkinter import *
win=Tk()

def prnt(arg):
    lbl.config(text=arg)

Button(width=2,state=DISABLED).grid(row=0,column=0)
Button(text="A",width=8,state=DISABLED).grid(row=0,column=1)
Button(text="B",width=8,state=DISABLED).grid(row=0,column=2)
Button(text="C",width=8,state=DISABLED).grid(row=0,column=3)
Button(text="D",width=8,state=DISABLED).grid(row=0,column=4)
Button(text="1",width=2,height=4,state=DISABLED).grid(row=1,column=0)
Button(bg='#ffffff',width=8,height=4,command=lambda: prnt("A1")).grid(row=1,column=1)
Button(bg='#000000',width=8,height=4,command=lambda: prnt("B1")).grid(row=1,column=2)
Button(bg='#ffffff',width=8,height=4,command=lambda: prnt("C1")).grid(row=1,column=3)
Button(bg='#000000',width=8,height=4,command=lambda: prnt("D1")).grid(row=1,column=4)
Button(text="2",width=2,height=4,state=DISABLED).grid(row=2,column=0)
Button(bg='#000000',width=8,height=4,command=lambda: prnt("A2")).grid(row=2,column=1)
Button(bg='#ffffff',width=8,height=4,command=lambda: prnt("B2")).grid(row=2,column=2)
Button(bg='#000000',width=8,height=4,command=lambda: prnt("C2")).grid(row=2,column=3)
Button(bg='#ffffff',width=8,height=4,command=lambda: prnt("D2")).grid(row=2,column=4)
Button(text="3",width=2,height=4,state=DISABLED).grid(row=3,column=0)
Button(bg='#ffffff',width=8,height=4,command=lambda: prnt("A3")).grid(row=3,column=1)
Button(bg='#000000',width=8,height=4,command=lambda: prnt("B3")).grid(row=3,column=2)
Button(bg='#ffffff',width=8,height=4,command=lambda: prnt("C3")).grid(row=3,column=3)
Button(bg='#000000',width=8,height=4,command=lambda: prnt("D3")).grid(row=3,column=4)
Button(text="4",width=2,height=4,state=DISABLED).grid(row=4,column=0)
Button(bg='#000000',width=8,height=4,command=lambda: prnt("A4")).grid(row=4,column=1)
Button(bg='#ffffff',width=8,height=4,command=lambda: prnt("B4")).grid(row=4,column=2)
Button(bg='#000000',width=8,height=4,command=lambda: prnt("C4")).grid(row=4,column=3)
Button(bg='#ffffff',width=8,height=4,command=lambda: prnt("D4")).grid(row=4,column=4)
lbl=Label(text="",width=10,font=("",30))
lbl.grid(row=0,column=5,rowspan=4)
win.mainloop()