from tkinter import *
window=Tk()
window.title("Анкета")
window.geometry("300x410")
window["bg"]="#FFF8DC"

fun=""
def save():
    global fun
    fun = str(var1.get()) + str(var2.get()) + str(var3.get())
    text.grid()
    fio=entr1.get()
    text.insert(1.0,"ФИО: "+str(fio))
    yer=entr2.get()
    text.insert(2.0,"\nГод рождения: "+str(yer))
    text.insert(3.0,"\nРазвлечения:"+fun)
    if var4.get()==0:
        text.insert(4.0,"\nPython Да")
    else:
        text.insert(4.0, "\nPython Нет")

lblframe=LabelFrame(text="Общие данные", bg="#FFE4B4",font=("",10,"bold"))
lblframe.grid(padx=3)
lblframe2=LabelFrame(text="О интересах", bg="#FFA089",font=("",10,"bold"))
lblframe2.grid(padx=3,pady=3)
img=PhotoImage(file="Inab.gif")
lbl1=Label(lblframe,image=img,width=60,height=80)
lbl1.grid(rowspan=2)
lbl2=Label(lblframe,text="ФИО")
lbl2.grid(row=0,column=1,padx=20)
lbl3=Label(lblframe,text="Год рождения")
lbl3.grid(row=1,column=1,padx=5)
entr1=Entry(lblframe)
entr1.grid(row=0,column=2,padx=5)
entr2=Entry(lblframe)
entr2.grid(row=1, column=2,padx=5)
lbl3=Label(lblframe2,text="Развлечения")
lbl3.grid(row=2, column=0)
var1=StringVar()
chek1=Checkbutton(lblframe2,text="Кино",variable=var1,onvalue="Кино ",offvalue="",bg="#FFA089")
chek1.grid(row=2,column=1,padx=5)
var2=StringVar()
chek2=Checkbutton(lblframe2,text="Вино",variable=var2,onvalue="Вино ",offvalue="",bg="#FFA089")
chek2.grid(row=2,column=2,padx=5)
var3=StringVar()
chek3=Checkbutton(lblframe2,text="Домино",variable=var3,onvalue="Домино ",offvalue="",bg="#FFA089")
chek3.grid(row=2,column=3,padx=5)
lbl4=Label(lblframe2,text="Нравится \n ли \n Puthon?",height=3,width=10)
lbl4.grid(row=3,column=0)
var4=IntVar()
var4.set(0)
rdb1=Radiobutton(lblframe2,text="Да",variable=var4,value=0,bg="#FFA089")
rdb1.grid(row=3,column=1)
rdb2=Radiobutton(lblframe2,text="Нет",variable=var4,value=1,bg="#FFA089")
rdb2.grid(row=3,column=2)
btn=Button(text="Принять",command=save)
btn.grid(row=4)
text=Text(width=20,height=10, wrap=WORD)
text.grid(row=5,pady=4)
text.grid_remove()

window.mainloop()